### ISSUE TITLE
Hopper / Dropper support

### ISSUE THREAD

**Issue by ikafly144** [plasmoapp/pv-addon-discs#26]
At this time, playing records using a hopper or dropper and retrieving records using a hopper are not working properly.

**Comment by ProjectHSI** [comment]
Can confirm this happens. Particles come from the Jukebox but there is no confirmation of sound (Loading action bar text / Title action bar text (e.g. the name of the record)) and no sound is ever played.

I think this is due to [JukeboxEventListener's onHopperInsertToJukebox event](https://github.com/plasmoapp/pv-addon-discs/blob/03be0f5c7180f829aaeb34a7f8389a71b184685a/src/main/kotlin/su/plo/voice/discs/event/JukeboxEventListener.kt#L39) not being sufficient enough. I don't believe anything on my server is cancelling the event.

One possible solution is to use [org.bukkit.event.inventory.InventoryMoveItemEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/inventory/InventoryMoveItemEvent.html), white sub-optimal as we would need to add more, it's possible it could work.

**Comment by MagmaBro123** [comment]
Dead project, won't happen.

**Comment by Danrejk** [comment]
Please! This is the single best thing about plasmo voice!

**Comment by ProjectHSI** [comment]
@MagmaBro123 I think the devs might not have time to fix the problems here, that or they forgot the issues tab exists. The project is still getting updated. (You can see via the commit messages.)

**Comment by Apehum** [comment]
Sorry for the really late response. Hoppers and droppers should be supported in the [prerelease](https://github.com/plasmoapp/pv-addon-discs/releases/tag/1.0.6).

Tested with the latest version of mc 1.20.4, and everything is working fine: https://youtu.be/04FMQC0EBT4

**Comment by ProjectHSI** [comment]
> Sorry for the really late response.

It's OK. Some of my issues never get resolved.
